# Generated by Django 4.1 on 2022-09-02 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_tag_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=7)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=200)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('place_quantity', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Сounterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('inn_document', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='order',
            name='from_organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='testing.сounterparty'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.profile'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='testing.сounterparty'),
        ),
        migrations.AddField(
            model_name='detail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.order'),
        ),
    ]
