# Generated by Django 4.1 on 2022-09-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_detail_order_сounterparty_delete_post_delete_tag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сounterparty',
            new_name='Counterparty',
        ),
    ]
